version: '3'
services:
  app:
    container_name: spring-boot-bcp
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: mvn clean spring-boot:run
