DELETE FROM COIN;
DELETE FROM ROL;
DELETE FROM USUARIO;

INSERT INTO COIN (DESCRIPTION, VALUE) VALUES ('DOLAR', 3.45), ('EURO', 4.02), ('NUEVO SOL', 2.01);
INSERT INTO ROL (ROL_NOMBRE) VALUES ('ROLE_ADMIN'),('ROLE_USER');
INSERT INTO USUARIO (NOMBRE,EMAIL,NOMBRE_USUARIO, PASSWORD) VALUES ('admin','rlozada1994@gmail.com','admin','$2a$10$FnVCIs3ENlcf0AuOO6aGK.hCUDiGLYuF2pexzQ/pVmkniXbKV2U2K');
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1,1),(1,2)
