DROP TABLE IF EXISTS COIN;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;
DROP TABLE IF EXISTS USUARIO_ROL;

CREATE TABLE COIN(
ID INT PRIMARY KEY auto_increment,
DESCRIPTION VARCHAR(100),
VALUE NUMBER (5,2)
);

CREATE TABLE USUARIO(
ID INT PRIMARY KEY auto_increment,
EMAIL VARCHAR(255),
NOMBRE VARCHAR(255),
NOMBRE_USUARIO VARCHAR(255),
PASSWORD VARCHAR(255)
);

CREATE TABLE ROL(
ID INT PRIMARY KEY auto_increment,
ROL_NOMBRE VARCHAR(255)
);

CREATE TABLE USUARIO_ROL(
USUARIO_ID INT,
ROL_ID INT,
foreign key (ROL_ID) references ROL(ID)
);
